### ISSUE TITLE
Read contact name

### ISSUE THREAD

**Issue by erdnaxeli** [tijder/SmsMatrix#2]
The app could (if permission is given) read the contacts directory, find the contact name and use it instead of the number.

Also you could use it to set the rame name instead of only the topic.

**Comment by MurzNN** [comment]
We can set custom name of bot per room: https://matrix.to/#/!svJUttHBtRMdXmEhEy:matrix.org/$15078026512030CsJBl:cervoi.se
So we can keep room name empty and rename bot in room, and in Riot interface we will see contact number or name in room list.
