### ISSUE TITLE
Incoming SMS not bridged

### ISSUE THREAD

**Issue by tulir** [tijder/SmsMatrix#27]
After moving to a new phone, incoming SMS doesn't get bridged to Matrix at all. Messages sent to previously created rooms are bridged to SMS just fine.

The only related thing I could find in logcat is this:
```
11-14 20:26:26.148  1092  1112 W BroadcastQueue: Permission Denial: receiving Intent { act=android.provider.Telephony.SMS_RECEIVED flg=0x19000010 (has extras) } to eu.droogers.smsmatrix/.ReceiverListener requires android.permission.RECEIVE_SMS due to sender com.android.phone (uid 1001)
```

The app has all the permissions. I tried both the latest release and a self-compiled version from a few days back.

Huawei P20 Pro / Android 8.1

**Comment by untidylamp** [comment]
Try now @tulir 

I'm learning Java and Android dev while trying to fix bugs in this app   :)

**Comment by tulir** [comment]
Looks like it works now, thanks!
