### ISSUE TITLE
Ask permissions in the app

### ISSUE THREAD

**Issue by tijder** [tijder/SmsMatrix#6]

**Comment by Gredin67** [comment]
I guess this problem has been solved in the last version, as I have been asked successively for separate permissions for : 
- SMS 
- Calls
- Contacts
- Photo, storage, taking video for videocalls
I did not give the last authorization and the functionalities that are not related work fine.

**Comment by tijder** [comment]
Solved in pull request #30. It is only not possible to start the app without giving all the permissions.
