### ISSUE TITLE
Set SMS sender number or contact name as room name in SmsMatrix rooms

### ISSUE THREAD

**Issue by MurzNN** [tijder/SmsMatrix#7]
At now SmsMatrix create room and set SMS sender phone number in room topic. Will be good to see it in room name, and if we have contact name from Android addressbook - set contact name instead of phone number, and keep number in room topic.

**Comment by tulir** [comment]
Isn't this mostly a duplicate of #2?

**Comment by MurzNN** [comment]
yes, dup of #2
