### ISSUE TITLE
ATTENTION: SMS Matrix labeled "Suspicious" per VirusTotal - several flags raised upon APK scan

### ISSUE THREAD

**Issue by boognish-rising** [tijder/SmsMatrix#86]
Not sure if this is cause for concern or not as I haven't yet had a chance to dig deeper into the claims or determine whether the "suspicious" label given to SMS Matrix upon scanning with VirusTotal is deserved but in the interim, I figured I'd put this here so that if an opportunity presents itself for someone else that has the time/ability to do so sooner than I'm able to and/or to bring to maintainer's attention (unless it's completely abandoned, in which case if the suspicions prove legit, would effectively serve as a death sentence IMO)

Let me know if you find one way or another and I'll amend this issue/post accordingly:

[mailto:paulson@paulson.anonaddy.com](email me) 

https://www.virustotal.com/en/file/728c35b687316efaec204509444ff37b0f14a2fb1156ef6573266427a7618bd4/analysis/ #VTMobile

![Screenshot_20220710-214855.png](https://user-images.githubusercontent.com/76668060/178173749-f3e1da9b-f019-42bf-a78e-d20b4bbfdc7b.png)

![Screenshot_20220710-214906.png](https://user-images.githubusercontent.com/76668060/178173876-e0971cfb-5ebf-4f63-92ff-0f3b68efecb3.png)

![Screenshot_20220710-214915.png](https://user-images.githubusercontent.com/76668060/178173899-eae729c4-3a09-4561-a870-c99d5ee212c5.png)

![Screenshot_20220710-214932.png](https://user-images.githubusercontent.com/76668060/178173913-c624a81c-8a54-4bfd-a8b8-31103f06fb18.png)

**Comment by G2G2G2G** [comment]
this thread is hilarious eye into the winbaby's average life. Why do you kind of people even bother using computers?

natzki's post literally makes no sense. You'd need a PhD to decipher that crap.

Anyway here it is on f droid which is generally reviewed
https://f-droid.org/en/packages/eu.droogers.smsmatrix/
Go in the source and link to your trojan.. the code base for this app isn't that big.
That trojan, by name, is because it can send/read SMS messages...

**Comment by boognish-rising** [comment]
Ok, dipshit. I literally opened my comment and this thread with, "not sure if this is cause for concern or not [...]"

What do you suppose that could mean? Do you think it's possible that I was leaving room for the "suspicious" label to be unwarranted and therefore not cause for concern? Let's see if anything else supports that notion, shall we, smart guy?

Oh hey! What do you know? The very next thing I said happened to be, "as I haven't yet had a chance to dig deeper into the claims or **determine whether the "suspicious" label given to SMS Matrix upon scanning with VirusTotal is deserved**" 

You seem to have a handle on everything. What do you think those words strung together in the order that they were mean, buddy? Bc judging by your comment, one would think that this is all wide open for debate. However, it looks to me like you're just a dipshit and like to hear yourself talk because in no world could one read what I wrote and arrive at the conclusion that you did, which motivated you to spew a bunch of nonsensical bullshit. 

It's all good though. You're comment isn't completely worthless; it provides a nice window into the life of a troll. I've always been fascinated by those creatures. 



PS - wtf is a winbaby? I think you were going for whiny baby... maybe? I don't know because you were way off and it's anybody's guess what the fuck you're on about. As far as a casual onlooker can tell, you're either out of your element _all the time_ or just when you post comments on GitHub because there was literally zero justification for your comment and yet, when it was all said and done you thought, "Yeah, why don't I go ahead and say these stupid-ass words. They'll surely resonate with somebody."

Dumbass

**Comment by boognish-rising** [comment]
Ok, dipshit. I literally opened my comment and this thread with, "not sure if this is cause for concern or not [...]"

What do you suppose that could mean? Do you think it's possible that I was leaving room for the "suspicious" label to be unwarranted and therefore not cause for concern? Let's see if anything else supports that notion, shall we, smart guy?

Oh hey! What do you know? The very next thing I said happened to be, "as I haven't yet had a chance to dig deeper into the claims or **determine whether the "suspicious" label given to SMS Matrix upon scanning with VirusTotal is deserved**" 

You seem to have a handle on everything. What do you think those words strung together in the order that they were mean, buddy? Bc judging by your comment, one would think that this is all wide open for debate. However, it looks to me like you're just a dipshit and like to hear yourself talk because in no world could one read what I wrote and arrive at the conclusion that you did, which motivated you to spew a bunch of nonsensical bullshit. 

It's all good though. You're comment isn't completely worthless; it provides a nice window into the life of a troll. I've always been fascinated by those creatures. 



PS - wtf is a winbaby? I think you were going for whiny baby... maybe? I don't know because you were way off and it's anybody's guess what the fuck you're on about. As far as a casual onlooker can tell, you're either out of your element _all the time_ or just when you post comments on GitHub because there was literally zero justification for your comment and yet, when it was all said and done you thought, "Yeah, why don't I go ahead and say these stupid-ass words. They'll surely resonate with somebody."

Dumbass

**Comment by tijder** [comment]
I'm closing this issue. Its becoming to off topic. I don't see any security problems. Only that it is using sms permissions.
