### ISSUE TITLE
Provide info about SmsMatrix in Matrix.org application service list

### ISSUE THREAD

**Issue by MurzNN** [tijder/SmsMatrix#9]
Will be good to provide info about SmsMatrix in Matrix.org application service list https://matrix.org/docs/projects/try-matrix-now.html#application-services
This can be done via pull request with creating new description file in https://github.com/matrix-org/matrix-doc/tree/master/supporting-docs/projects folder, here is example: https://github.com/matrix-org/matrix-doc/pull/974

**Comment by tijder** [comment]
I created a pull request https://github.com/matrix-org/matrix-doc/pull/1018.

**Comment by tijder** [comment]
It's merged.
